//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::idea_status::IdeaStatus;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "idea")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub initiator_id: Uuid,
    pub name: String,
    pub group_expert_id: Option<Uuid>,
    pub group_project_office_id: Option<Uuid>,
    pub status: IdeaStatus,
    pub is_active: bool,
    pub problem: Option<String>,
    pub solution: Option<String>,
    pub result: Option<String>,
    pub customer: Option<String>,
    pub contact_person: Option<String>,
    pub description: Option<String>,
    pub suitability: Option<i64>,
    pub budget: Option<i64>,
    pub max_team_size: Option<i16>,
    pub min_team_size: Option<i16>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pre_assessment: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rating: Option<f64>,
    pub created_at: DateTimeWithTimeZone,
    pub modified_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "Group2",
        from = "group_expert_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub group_2: HasOne<super::group::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Group1",
        from = "group_project_office_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub group_1: HasOne<super::group::Entity>,
    #[sea_orm(has_many, via = "idea_skill")]
    pub skills: HasMany<super::skill::Entity>,
    #[sea_orm(belongs_to, from = "initiator_id", to = "id")]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
