//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::idea_status::IdeaStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "idea")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub initiator_id: Uuid,
    pub name: String,
    pub group_expert_id: Uuid,
    pub group_project_office_id: Uuid,
    pub status: IdeaStatus,
    pub is_active: bool,
    pub problem: String,
    pub solution: String,
    pub result: String,
    pub customer: String,
    pub contact_person: String,
    pub description: String,
    pub suitability: i64,
    pub budget: i64,
    pub max_team_size: i16,
    pub min_team_size: i16,
    #[sea_orm(column_type = "Double")]
    pub pre_assessment: f64,
    #[sea_orm(column_type = "Double")]
    pub rating: f64,
    pub created_at: DateTimeWithTimeZone,
    pub modified_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        relation_enum = "Experts",
        from = "group_expert_id",
        to = "id"
    )]
    pub experts: HasOne<super::group::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ProjectOffice",
        from = "group_project_office_id",
        to = "id"
    )]
    pub project_office: HasOne<super::group::Entity>,
    #[sea_orm(has_many)]
    pub idea_markets: HasMany<super::idea_market::Entity>,
    #[sea_orm(has_one)]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(has_many)]
    pub ratings: HasMany<super::rating::Entity>,
    #[sea_orm(has_many, via = "idea_skill")]
    pub skills: HasMany<super::skill::Entity>,
    #[sea_orm(belongs_to, from = "initiator_id", to = "id")]
    pub initiator: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
