//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::role::Role;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "invitation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub roles: Vec<Role>,
    #[sea_orm(unique)]
    pub email: String,
    pub expiry_date: DateTimeWithTimeZone,
}

impl ActiveModelBehavior for ActiveModel {}
