//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub mod prelude;

pub mod company;
pub mod company_member;
pub mod favorite_idea;
pub mod group;
pub mod group_member;
pub mod idea;
pub mod idea_checked;
pub mod idea_market;
pub mod idea_market_advertisement;
pub mod idea_market_refused;
pub mod idea_market_status;
pub mod idea_skill;
pub mod idea_status;
pub mod invitation;
pub mod market;
pub mod market_status;
pub mod project;
pub mod project_status;
pub mod rating;
pub mod request_status;
pub mod role;
pub mod skill;
pub mod skill_type;
pub mod team;
pub mod team_market_request;
pub mod team_member;
pub mod team_refused;
pub mod team_wanted_skill;
pub mod user_skill;
pub mod users;
pub mod verification_code;
pub mod team_invitation;