//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::market_status::MarketStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "market")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub start_date: Date,
    pub finish_date: Date,
    pub status: MarketStatus,
    #[sea_orm(has_many)]
    pub idea_markets: HasMany<super::idea_market::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
