//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub use super::invitation::Entity as Invitation;
pub use super::role::Role;
pub use super::users::Entity as Users;
pub use super::verification_code::Entity as VerificationCode;
