//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::project_role::ProjectRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "project_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub project_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub team_id: Option<Uuid>,
    pub project_role: ProjectRole,
    pub start_date: Date,
    pub finish_date: Option<Date>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub team: HasOne<super::team::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
