//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::project_status::ProjectStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub idea_id: Uuid,
    #[sea_orm(unique)]
    pub team_id: Uuid,
    pub status: ProjectStatus,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub report: Option<String>,
    pub start_date: Date,
    pub finish_date: Option<Date>,
    #[sea_orm(
        belongs_to,
        from = "idea_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub idea: HasOne<super::idea::Entity>,
    #[sea_orm(has_many)]
    pub project_members: HasMany<super::project_member::Entity>,
    #[sea_orm(has_many)]
    pub sprints: HasMany<super::sprint::Entity>,
    #[sea_orm(has_many)]
    pub sprint_marks: HasMany<super::sprint_mark::Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::task::Entity>,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub team: HasOne<super::team::Entity>,
    #[sea_orm(has_many, via = "project_marks")]
    pub users: HasMany<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
