//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::project_status::ProjectStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub idea_id: Uuid,
    #[sea_orm(unique)]
    pub team_id: Uuid,
    pub status: ProjectStatus,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "idea_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub idea: HasOne<super::idea::Entity>,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub team: HasOne<super::team::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
