//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "rating")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub idea_id: Uuid,
    pub expert_id: Uuid,
    #[sea_orm(column_type = "Double")]
    pub rating: f64,
    pub budget: i64,
    pub market_value: i64,
    pub originality: i64,
    pub technical_realizability: i64,
    pub suitability: i64,
    pub is_confirmed: bool,
    #[sea_orm(belongs_to, from = "expert_id", to = "id")]
    pub expert: HasOne<super::users::Entity>,
    #[sea_orm(belongs_to, from = "idea_id", to = "id")]
    pub idea: HasOne<super::idea::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
