//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::skill_type::SkillType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "skill")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub skill_type: SkillType,
    pub confirmed: bool,
    pub creator_id: Uuid,
    pub updater_id: Option<Uuid>,
    pub deleter_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many, via = "idea_skill")]
    pub ideas: HasMany<super::idea::Entity>,
    #[sea_orm(has_many, via = "user_skill")]
    pub users: HasMany<super::users::Entity>,
    // #[sea_orm(has_many)]
    // pub user_skills: HasMany<super::user_skill::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
