//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::skill_type::SkillType;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "skill")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub skill_type: SkillType,
    pub confirmed: bool,
    pub creator_id: Uuid,
    pub updater_id: Option<Uuid>,
    pub deleter_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users3",
        from = "creator_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users_3: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "deleter_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "updater_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_1: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
