//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::sprint_status::SprintStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sprint")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub goal: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub report: Option<String>,
    pub start_date: Date,
    pub finish_date: Option<Date>,
    pub working_hours: Option<i64>,
    pub status: SprintStatus,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(has_many)]
    pub sprint_marks: HasMany<super::sprint_mark::Entity>,
    #[sea_orm(has_many)]
    pub tasks: HasMany<super::task::Entity>,
    #[sea_orm(has_many)]
    pub task_histories: HasMany<super::task_history::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
