//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::project_role::ProjectRole;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sprint_mark")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    pub sprint_id: Uuid,
    pub user_id: Uuid,
    pub project_role: ProjectRole,
    #[sea_orm(column_type = "Double", nullable)]
    pub mark: Option<f64>,
    pub count_completed_tasks: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(
        belongs_to,
        from = "sprint_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub sprint: HasOne<super::sprint::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
