//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub color: String,
    pub confirmed: bool,
    pub creator_id: Option<Uuid>,
    pub updater_id: Option<Uuid>,
    pub deleter_id: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users3",
        from = "creator_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_3: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "deleter_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "updater_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_1: HasOne<super::users::Entity>,
    #[sea_orm(has_many, via = "task_tag")]
    pub tasks: HasMany<super::task::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
