//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::task_status::TaskStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub task_id: Uuid,
    pub sprint_id: Option<Uuid>,
    pub status: Option<TaskStatus>,
    pub executor_id: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        from = "sprint_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub sprint: HasOne<super::sprint::Entity>,
    #[sea_orm(
        belongs_to,
        from = "task_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub task: HasOne<super::task::Entity>,
    #[sea_orm(
        belongs_to,
        from = "executor_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
