//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::task_status::TaskStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub sprint_id: Option<Uuid>,
    pub project_id: Uuid,
    pub position: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub leader_comment: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub executor_comment: Option<String>,
    pub initiator_id: Option<Uuid>,
    pub executor_id: Option<Uuid>,
    #[sea_orm(column_type = "Double", nullable)]
    pub work_hour: Option<f64>,
    pub start_date: Date,
    pub finish_date: Option<Date>,
    pub status: Option<TaskStatus>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub project: HasOne<super::project::Entity>,
    #[sea_orm(
        belongs_to,
        from = "sprint_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub sprint: HasOne<super::sprint::Entity>,
    #[sea_orm(has_many)]
    pub task_histories: HasMany<super::task_history::Entity>,
    #[sea_orm(has_many)]
    pub task_movement_logs: HasMany<super::task_movement_log::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "executor_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "initiator_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub users_1: HasOne<super::users::Entity>,
    #[sea_orm(has_many, via = "task_tag")]
    pub tags: HasMany<super::tag::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
