//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "team_wanted_skill")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub team_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub skill_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub team: HasOne<super::team::Entity>,
    #[sea_orm(
        belongs_to,
        from = "skill_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub skill: HasOne<super::skill::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
