//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: String,
    pub created_at: DateTimeWithTimeZone,
    pub is_closed: bool,
    pub owner_id: Uuid,
    pub leader_id: Option<Uuid>,
    pub has_active_project: bool,
    pub is_deleted: bool,

    #[sea_orm(has_many)]
    pub wanted_skills: HasMany<super::team_wanted_skill::Entity>,
    #[sea_orm(has_many)]
    pub team_members: HasMany<super::team_member::Entity>,
    #[sea_orm(belongs_to, relation_enum = "TeamLeader", from = "LeaderId", to = "Id")]
    pub leader: HasOne<super::users::Entity>,
    #[sea_orm(belongs_to, relation_enum = "TeamOwner", from = "OwnerId", to = "Id")]
    pub owner: HasOne<super::users::Entity>,
    #[sea_orm(has_many, via = "team_member")]
    pub members: HasMany<super::users::Entity>,
}
impl ActiveModelBehavior for ActiveModel {}
