//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::request_status::RequestStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "team_market_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub team_id: Uuid,
    pub idea_market_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub letter: Option<String>,
    pub status: RequestStatus,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "idea_market_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub idea_market: HasOne<super::idea_market::Entity>,
    #[sea_orm(
        belongs_to,
        from = "team_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub team: HasOne<super::team::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
