//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::role::Role;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub study_group: Option<String>,
    pub telephone: Option<String>,
    pub roles: Vec<Role>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub last_name: String,
    pub first_name: String,
    pub created_at: DateTimeWithTimeZone,
    pub is_deleted: bool,
    #[sea_orm(has_many)]
    pub idea_market_advertisements: HasMany<super::idea_market_advertisement::Entity>,
    #[sea_orm(has_many)]
    pub ratings: HasMany<super::rating::Entity>,
    #[sea_orm(has_many, via = "company_member")]
    pub companies: HasMany<super::company::Entity>,
    #[sea_orm(has_many)]
    pub company_members: HasMany<super::company_member::Entity>,
    #[sea_orm(has_many, via = "group_member")]
    pub groups: HasMany<super::group::Entity>,
    #[sea_orm(has_many, via = "idea_checked")]
    pub ideas: HasMany<super::idea::Entity>,
    #[sea_orm(has_many, via = "favorite_idea")]
    pub idea_markets: HasMany<super::idea_market::Entity>,
    #[sea_orm(has_many, via = "user_skill")]
    pub skills: HasMany<super::skill::Entity>,
    #[sea_orm(has_many)]
    pub user_skills: HasMany<super::user_skill::Entity>,
    #[sea_orm(has_many)]
    pub team_members: HasMany<super::team_member::Entity>,
    #[sea_orm(has_many)]
    pub project_members: HasMany<super::project_member::Entity>,
    #[sea_orm(has_many)]
    pub sprint_marks: HasMany<super::sprint_mark::Entity>,
    #[sea_orm(has_many)]
    pub task_histories: HasMany<super::task_history::Entity>,
    #[sea_orm(has_many)]
    pub team_invitations: HasMany<super::team_invitation::Entity>,
    #[sea_orm(has_many)]
    pub team_refuseds: HasMany<super::team_refused::Entity>,
    #[sea_orm(has_many, via = "project_marks")]
    pub projects: HasMany<super::project::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
