//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use crate::role::Role;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub study_group: Option<String>,
    pub telephone: Option<String>,
    pub roles: Vec<Role>,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub last_name: String,
    pub first_name: String,
    pub created_at: DateTimeWithTimeZone,
    pub is_deleted: bool,
    #[sea_orm(has_many, via = "company_member")]
    pub companies: HasMany<super::company::Entity>,
    #[sea_orm(has_many, via = "group_member")]
    pub groups: HasMany<super::group::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
